/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DmRouteImport } from './routes/dm'
import { Route as ConfessionsRouteImport } from './routes/confessions'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DmUserIdRouteImport } from './routes/dm.$userId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DmRoute = DmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfessionsRoute = ConfessionsRouteImport.update({
  id: '/confessions',
  path: '/confessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmUserIdRoute = DmUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => DmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/confessions': typeof ConfessionsRoute
  '/dm': typeof DmRouteWithChildren
  '/games': typeof GamesRoute
  '/gifts': typeof GiftsRoute
  '/login': typeof LoginRoute
  '/wallet': typeof WalletRoute
  '/dm/$userId': typeof DmUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/confessions': typeof ConfessionsRoute
  '/dm': typeof DmRouteWithChildren
  '/games': typeof GamesRoute
  '/gifts': typeof GiftsRoute
  '/login': typeof LoginRoute
  '/wallet': typeof WalletRoute
  '/dm/$userId': typeof DmUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/confessions': typeof ConfessionsRoute
  '/dm': typeof DmRouteWithChildren
  '/games': typeof GamesRoute
  '/gifts': typeof GiftsRoute
  '/login': typeof LoginRoute
  '/wallet': typeof WalletRoute
  '/dm/$userId': typeof DmUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/confessions'
    | '/dm'
    | '/games'
    | '/gifts'
    | '/login'
    | '/wallet'
    | '/dm/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/confessions'
    | '/dm'
    | '/games'
    | '/gifts'
    | '/login'
    | '/wallet'
    | '/dm/$userId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/confessions'
    | '/dm'
    | '/games'
    | '/gifts'
    | '/login'
    | '/wallet'
    | '/dm/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ConfessionsRoute: typeof ConfessionsRoute
  DmRoute: typeof DmRouteWithChildren
  GamesRoute: typeof GamesRoute
  GiftsRoute: typeof GiftsRoute
  LoginRoute: typeof LoginRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm': {
      id: '/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof DmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confessions': {
      id: '/confessions'
      path: '/confessions'
      fullPath: '/confessions'
      preLoaderRoute: typeof ConfessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm/$userId': {
      id: '/dm/$userId'
      path: '/$userId'
      fullPath: '/dm/$userId'
      preLoaderRoute: typeof DmUserIdRouteImport
      parentRoute: typeof DmRoute
    }
  }
}

interface DmRouteChildren {
  DmUserIdRoute: typeof DmUserIdRoute
}

const DmRouteChildren: DmRouteChildren = {
  DmUserIdRoute: DmUserIdRoute,
}

const DmRouteWithChildren = DmRoute._addFileChildren(DmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ConfessionsRoute: ConfessionsRoute,
  DmRoute: DmRouteWithChildren,
  GamesRoute: GamesRoute,
  GiftsRoute: GiftsRoute,
  LoginRoute: LoginRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
