/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SupabaseTestRouteImport } from './routes/supabase-test'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as MalayalamVoiceChatRouteImport } from './routes/malayalam-voice-chat'
import { Route as MalayalamChatRoomRouteImport } from './routes/malayalam-chat-room'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GulfMalayaliChatRouteImport } from './routes/gulf-malayali-chat'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DmRouteImport } from './routes/dm'
import { Route as ConfessionsRouteImport } from './routes/confessions'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnonymousMalayalamChatRouteImport } from './routes/anonymous-malayalam-chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DmUserIdRouteImport } from './routes/dm.$userId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SupabaseTestRoute = SupabaseTestRouteImport.update({
  id: '/supabase-test',
  path: '/supabase-test',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const MalayalamVoiceChatRoute = MalayalamVoiceChatRouteImport.update({
  id: '/malayalam-voice-chat',
  path: '/malayalam-voice-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MalayalamChatRoomRoute = MalayalamChatRoomRouteImport.update({
  id: '/malayalam-chat-room',
  path: '/malayalam-chat-room',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GulfMalayaliChatRoute = GulfMalayaliChatRouteImport.update({
  id: '/gulf-malayali-chat',
  path: '/gulf-malayali-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DmRoute = DmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfessionsRoute = ConfessionsRouteImport.update({
  id: '/confessions',
  path: '/confessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousMalayalamChatRoute = AnonymousMalayalamChatRouteImport.update({
  id: '/anonymous-malayalam-chat',
  path: '/anonymous-malayalam-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmUserIdRoute = DmUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => DmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/anonymous-malayalam-chat': typeof AnonymousMalayalamChatRoute
  '/chat': typeof ChatRoute
  '/confessions': typeof ConfessionsRoute
  '/dm': typeof DmRouteWithChildren
  '/games': typeof GamesRoute
  '/gifts': typeof GiftsRoute
  '/gulf-malayali-chat': typeof GulfMalayaliChatRoute
  '/login': typeof LoginRoute
  '/malayalam-chat-room': typeof MalayalamChatRoomRoute
  '/malayalam-voice-chat': typeof MalayalamVoiceChatRoute
  '/podcasts': typeof PodcastsRoute
  '/profile': typeof ProfileRoute
  '/radio': typeof RadioRoute
  '/supabase-test': typeof SupabaseTestRoute
  '/wallet': typeof WalletRoute
  '/dm/$userId': typeof DmUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/anonymous-malayalam-chat': typeof AnonymousMalayalamChatRoute
  '/chat': typeof ChatRoute
  '/confessions': typeof ConfessionsRoute
  '/dm': typeof DmRouteWithChildren
  '/games': typeof GamesRoute
  '/gifts': typeof GiftsRoute
  '/gulf-malayali-chat': typeof GulfMalayaliChatRoute
  '/login': typeof LoginRoute
  '/malayalam-chat-room': typeof MalayalamChatRoomRoute
  '/malayalam-voice-chat': typeof MalayalamVoiceChatRoute
  '/podcasts': typeof PodcastsRoute
  '/profile': typeof ProfileRoute
  '/radio': typeof RadioRoute
  '/supabase-test': typeof SupabaseTestRoute
  '/wallet': typeof WalletRoute
  '/dm/$userId': typeof DmUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/anonymous-malayalam-chat': typeof AnonymousMalayalamChatRoute
  '/chat': typeof ChatRoute
  '/confessions': typeof ConfessionsRoute
  '/dm': typeof DmRouteWithChildren
  '/games': typeof GamesRoute
  '/gifts': typeof GiftsRoute
  '/gulf-malayali-chat': typeof GulfMalayaliChatRoute
  '/login': typeof LoginRoute
  '/malayalam-chat-room': typeof MalayalamChatRoomRoute
  '/malayalam-voice-chat': typeof MalayalamVoiceChatRoute
  '/podcasts': typeof PodcastsRoute
  '/profile': typeof ProfileRoute
  '/radio': typeof RadioRoute
  '/supabase-test': typeof SupabaseTestRoute
  '/wallet': typeof WalletRoute
  '/dm/$userId': typeof DmUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/anonymous-malayalam-chat'
    | '/chat'
    | '/confessions'
    | '/dm'
    | '/games'
    | '/gifts'
    | '/gulf-malayali-chat'
    | '/login'
    | '/malayalam-chat-room'
    | '/malayalam-voice-chat'
    | '/podcasts'
    | '/profile'
    | '/radio'
    | '/supabase-test'
    | '/wallet'
    | '/dm/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/anonymous-malayalam-chat'
    | '/chat'
    | '/confessions'
    | '/dm'
    | '/games'
    | '/gifts'
    | '/gulf-malayali-chat'
    | '/login'
    | '/malayalam-chat-room'
    | '/malayalam-voice-chat'
    | '/podcasts'
    | '/profile'
    | '/radio'
    | '/supabase-test'
    | '/wallet'
    | '/dm/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/anonymous-malayalam-chat'
    | '/chat'
    | '/confessions'
    | '/dm'
    | '/games'
    | '/gifts'
    | '/gulf-malayali-chat'
    | '/login'
    | '/malayalam-chat-room'
    | '/malayalam-voice-chat'
    | '/podcasts'
    | '/profile'
    | '/radio'
    | '/supabase-test'
    | '/wallet'
    | '/dm/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AnonymousMalayalamChatRoute: typeof AnonymousMalayalamChatRoute
  ChatRoute: typeof ChatRoute
  ConfessionsRoute: typeof ConfessionsRoute
  DmRoute: typeof DmRouteWithChildren
  GamesRoute: typeof GamesRoute
  GiftsRoute: typeof GiftsRoute
  GulfMalayaliChatRoute: typeof GulfMalayaliChatRoute
  LoginRoute: typeof LoginRoute
  MalayalamChatRoomRoute: typeof MalayalamChatRoomRoute
  MalayalamVoiceChatRoute: typeof MalayalamVoiceChatRoute
  PodcastsRoute: typeof PodcastsRoute
  ProfileRoute: typeof ProfileRoute
  RadioRoute: typeof RadioRoute
  SupabaseTestRoute: typeof SupabaseTestRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supabase-test': {
      id: '/supabase-test'
      path: '/supabase-test'
      fullPath: '/supabase-test'
      preLoaderRoute: typeof SupabaseTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malayalam-voice-chat': {
      id: '/malayalam-voice-chat'
      path: '/malayalam-voice-chat'
      fullPath: '/malayalam-voice-chat'
      preLoaderRoute: typeof MalayalamVoiceChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malayalam-chat-room': {
      id: '/malayalam-chat-room'
      path: '/malayalam-chat-room'
      fullPath: '/malayalam-chat-room'
      preLoaderRoute: typeof MalayalamChatRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gulf-malayali-chat': {
      id: '/gulf-malayali-chat'
      path: '/gulf-malayali-chat'
      fullPath: '/gulf-malayali-chat'
      preLoaderRoute: typeof GulfMalayaliChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm': {
      id: '/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof DmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confessions': {
      id: '/confessions'
      path: '/confessions'
      fullPath: '/confessions'
      preLoaderRoute: typeof ConfessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anonymous-malayalam-chat': {
      id: '/anonymous-malayalam-chat'
      path: '/anonymous-malayalam-chat'
      fullPath: '/anonymous-malayalam-chat'
      preLoaderRoute: typeof AnonymousMalayalamChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm/$userId': {
      id: '/dm/$userId'
      path: '/$userId'
      fullPath: '/dm/$userId'
      preLoaderRoute: typeof DmUserIdRouteImport
      parentRoute: typeof DmRoute
    }
  }
}

interface DmRouteChildren {
  DmUserIdRoute: typeof DmUserIdRoute
}

const DmRouteChildren: DmRouteChildren = {
  DmUserIdRoute: DmUserIdRoute,
}

const DmRouteWithChildren = DmRoute._addFileChildren(DmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AnonymousMalayalamChatRoute: AnonymousMalayalamChatRoute,
  ChatRoute: ChatRoute,
  ConfessionsRoute: ConfessionsRoute,
  DmRoute: DmRouteWithChildren,
  GamesRoute: GamesRoute,
  GiftsRoute: GiftsRoute,
  GulfMalayaliChatRoute: GulfMalayaliChatRoute,
  LoginRoute: LoginRoute,
  MalayalamChatRoomRoute: MalayalamChatRoomRoute,
  MalayalamVoiceChatRoute: MalayalamVoiceChatRoute,
  PodcastsRoute: PodcastsRoute,
  ProfileRoute: ProfileRoute,
  RadioRoute: RadioRoute,
  SupabaseTestRoute: SupabaseTestRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
